# Generated by Django 2.2.28 on 2026-02-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
